version: '3'

services:
    database:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=courses
            - POSTGRES_PASSWORD=264462
            - POSTGRES_DB=courses
        volumes:
            - pgdata:/data/postgres

    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - 6379:6379

    # app:
    #   build: .
    #   container_name: rentx
    #   restart: always
    #   ports:
    #     - 3333:3333
    #     - 9229:9229
    #   volumes:
    #     - .:/usr/app
    #   links:
    #     - database
    #   depends_on:
    #     - database

volumes:
    pgdata:
        driver: local
